name: Angular Calculator CI/CD
on:
  push:
    branches: [ main ]

jobs:
  automation-task:
    runs-on: self-hosted
    steps:
      - name: 1. Fetching code from GitHub
        uses: actions/checkout@v4
        
      - name: 2. Preparing Environment
        uses: actions/setup-node@v4
        with:
         node-version: '20'
      - name: 3. Install NOde Modules
        run: npm install

      - name: 4. Building the Application
        run: npm run build
      - name: 5. Final Status
        run: echo "Build completed successfully!"
       