name: Angular Calculator CI/CD
on:
  push:
    branches: [ main ]

jobs:
  automation-task:
    runs-on: self-hosted
    steps:
      - name: 1. Fetching code from GitHub
        uses: actions/checkout@v4
        
      - name: 2. Install Node Modules
        run: npm install

      - name: 3. Running Tests
        run: npm test -- --watch=false
        continue-on-error: true

      - name: 4. Building the Application
        run: npm run build -- --output-path=C:/releases/${{ github.sha}}

      - name: 5. IIS Switch
        shell: powershell
        run: |
          $linkPath= "C:\browser"
          $targetPath = "C:\releases\${{ github.sha }}\browser"
          Import-Module WebAdministration
          Stop-WebSite -Name "MyFirstApp"
          Start-Sleep -Seconds 3

          if (Test-Path $linkPath) {
            $item= Get-Item $linkPath
            if ($item.Attributes -match "ReparsePoint") {
              Remove-Item $linkPath -Force
            } else {
                Remove-Item $linkPath -Recurse -Force
            }
          }
          New-Item -ItemType Junction -Path $linkPath -Target $targetPath
          Start-WebSite -Name "MyFirstApp"